services:
  - type: web
    name: quick-order
    env: docker
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - key: PORT
        value: 7192
      - key: NODE_ENV
        value: production